"""Zone names and effects (traditional claims only). Order here is the order zones are listed in the app.

id: (name, nameZh, group, organIds, effect, effectZh)
"""

GROUPS = {
    "head": {"label": "Head & nerves", "labelZh": "头脑神经", "color": "#8E6CD9"},
    "senses": {"label": "Senses", "labelZh": "五官", "color": "#3F95D6"},
    "endocrine": {"label": "Glands", "labelZh": "内分泌", "color": "#D9A62E"},
    "respiratory": {"label": "Lungs", "labelZh": "呼吸", "color": "#E07F8A"},
    "heart": {"label": "Heart", "labelZh": "心", "color": "#D8434B"},
    "digestive": {"label": "Digestion", "labelZh": "消化", "color": "#E3873B"},
    "urinary": {"label": "Kidney", "labelZh": "泌尿", "color": "#2BA7A0"},
    "reproductive": {"label": "Reproductive", "labelZh": "生殖", "color": "#C46FA0"},
    "lymph": {"label": "Lymph & immune", "labelZh": "淋巴免疫", "color": "#5FA84E"},
    "musculoskeletal": {"label": "Spine & joints", "labelZh": "骨骼关节", "color": "#A0785A"},
}

LUNGS = ["lung-l", "lung-r"]
KIDNEYS = ["kidney-l", "kidney-r"]

TEXT = {
    # ---------------------------------------------------------------- palm
    "palm-brain": ("Brain", "大脑", "head", ["brain"],
                   "Thumb tip and pad. Pressed for headache, dizziness and poor sleep.",
                   "拇指末节指腹。按压用于头痛、头晕、失眠。"),
    "palm-pituitary": ("Pituitary", "垂体", "endocrine", ["brain"],
                       "Center of the thumb pad. Said to balance hormones.",
                       "拇指指腹正中。传统认为可调节内分泌。"),
    "palm-sinuses": ("Frontal sinuses", "额窦", "senses", ["sinuses"],
                     "Pads of the four finger tips. For a blocked nose, sinus pressure, frontal headache.",
                     "四指末节指腹。用于鼻塞、鼻窦胀痛、前额头痛。"),
    "palm-teeth": ("Teeth & jaw", "牙·颌", "senses", ["face"],
                   "Middle sections of the four fingers. Traditionally for toothache and jaw tension.",
                   "四指中节掌面。传统用于牙痛、下颌紧张。"),
    "palm-eyes": ("Eyes", "眼", "senses", ["eyes"],
                  "Base sections of the index and middle fingers. For tired, strained eyes.",
                  "食指、中指近节掌面。用于眼疲劳、干涩。"),
    "palm-ears": ("Ears", "耳", "senses", ["ears"],
                  "Base sections of the ring and little fingers. For ringing ears and ear ache.",
                  "无名指、小指近节掌面。用于耳鸣、耳痛。"),
    "palm-neck": ("Neck & throat", "颈项·咽喉", "musculoskeletal", ["throat", "larynx", "spine"],
                  "Base section of the thumb. For a stiff neck and a scratchy throat.",
                  "拇指近节。用于颈项僵硬、咽喉不适。"),
    "palm-thyroid": ("Thyroid", "甲状腺", "endocrine", ["thyroid"],
                     "Curved band from the thumb mound up to the thumb web. Said to regulate metabolism.",
                     "大鱼际至虎口的弧形带。传统认为可调节代谢。"),
    "palm-spine": ("Spine", "脊柱", "musculoskeletal", ["spine"],
                   "Outer edge of the thumb and its mound, down to the wrist. For back and neck ache.",
                   "拇指及大鱼际桡侧缘至腕。用于颈背腰痛。"),
    "palm-lungs": ("Lungs & bronchi", "肺·支气管", "respiratory", LUNGS,
                   "Pads just below the fingers, index to little. For coughs and chest tightness.",
                   "四指根下方的掌垫横带。用于咳嗽、胸闷。"),
    "palm-shoulder": ("Shoulder", "肩", "musculoskeletal", ["shoulders"],
                      "Little-finger edge at the knuckle. For stiff shoulders.",
                      "第5掌指关节尺侧。用于肩部僵硬酸痛。"),
    "palm-arm": ("Arm & elbow", "上肢·肘", "musculoskeletal", ["shoulders"],
                 "Little-finger edge of the palm, below the shoulder. For elbow and arm strain.",
                 "手掌尺侧缘，肩区下方。用于肘臂劳损。"),
    "palm-hip": ("Hip & knee", "髋·膝", "musculoskeletal", ["spine"],
                 "Little-finger edge of the lower palm. For hip and knee stiffness.",
                 "手掌尺侧缘下部。用于髋、膝僵硬。"),
    "palm-solar-plexus": ("Solar plexus", "腹腔神经丛", "head", ["stomach", "brain"],
                          "Center of the upper palm. Pressed to calm nerves and a tight stomach.",
                          "掌心上部正中。按压用于缓解紧张、胃部痉挛。"),
    "palm-heart": ("Heart", "心", "heart", ["heart"],
                   "Left hand only, below the ring and little fingers. For palpitations and restlessness.",
                   "仅左手，无名指、小指下方。用于心悸、心烦。"),
    "palm-spleen": ("Spleen", "脾", "digestive", ["spleen"],
                    "Left hand only, below the heart zone. TCM spleen: appetite, digestion, fatigue.",
                    "仅左手，心反射区下方。中医之脾：食欲、消化、乏力。"),
    "palm-liver": ("Liver", "肝", "digestive", ["liver"],
                   "Right hand only, below the ring and little fingers. Said to support detox and ease irritability.",
                   "仅右手，无名指、小指下方。传统认为可助肝排毒、平肝除烦。"),
    "palm-gallbladder": ("Gallbladder", "胆囊", "digestive", ["gallbladder"],
                         "Right hand only, inside the lower liver zone. For a bitter taste and fatty-food discomfort.",
                         "仅右手，肝反射区下部之中。用于口苦、油腻后不适。"),
    "palm-stomach": ("Stomach", "胃", "digestive", ["stomach"],
                     "Upper palm on the thumb side. For indigestion and bloating.",
                     "掌心上部桡侧。用于消化不良、胃胀。"),
    "palm-pancreas": ("Pancreas", "胰", "digestive", ["pancreas"],
                      "Below the stomach zone. Traditionally linked to blood sugar.",
                      "胃反射区下方。传统上与血糖调节相关。"),
    "palm-duodenum": ("Duodenum", "十二指肠", "digestive", ["stomach", "intestines"],
                      "Below the pancreas zone. For stomach ache after meals.",
                      "胰反射区下方。用于餐后胃痛、腹胀。"),
    "palm-adrenal": ("Adrenals", "肾上腺", "endocrine", ["adrenals"],
                     "Just above the kidney zone, center palm. Traditionally for inflammation and allergy.",
                     "掌心肾反射区上方。传统用于炎症、过敏。"),
    "palm-kidneys": ("Kidneys", "肾", "urinary", KIDNEYS,
                     "Center of the palm. For fatigue and lower-back ache.",
                     "掌心正中。用于疲劳、腰酸。"),
    "palm-ureter": ("Ureter", "输尿管", "urinary", KIDNEYS + ["bladder"],
                    "Line from the kidney zone to the bladder. For urinary discomfort.",
                    "肾至膀胱的斜线。用于排尿不畅。"),
    "palm-bladder": ("Bladder", "膀胱", "urinary", ["bladder"],
                     "Where the thumb mound meets the lower palm, above the wrist. For frequent urination.",
                     "大鱼际与掌根交界处。用于尿频。"),
    "palm-colon": ("Transverse colon", "横结肠", "digestive", ["intestines"],
                   "Band across the lower-middle palm. For constipation and wind.",
                   "掌中下部横带。用于便秘、腹胀。"),
    "palm-colon-asc": ("Ascending colon", "升结肠", "digestive", ["intestines"],
                       "Right hand only, little-finger side of the lower palm. For constipation.",
                       "仅右手，掌下部尺侧纵带。用于便秘。"),
    "palm-appendix": ("Appendix & ileocecal valve", "阑尾·回盲瓣", "digestive", ["appendix", "intestines"],
                      "Right hand only, bottom of the ascending colon. Traditionally for lower-right bloating.",
                      "仅右手，升结肠下端。传统用于右下腹胀。"),
    "palm-colon-desc": ("Descending & sigmoid colon", "降结肠·乙状结肠", "digestive", ["intestines"],
                        "Left hand only, down the little-finger side then across above the wrist. For constipation.",
                        "仅左手，掌下部尺侧下行再横过腕上。用于便秘。"),
    "palm-rectum": ("Rectum", "直肠·肛门", "digestive", ["intestines"],
                    "Left hand only, low center of the palm. For constipation and piles.",
                    "仅左手，掌根正中。用于便秘、痔疮。"),
    "palm-small-intestine": ("Small intestine", "小肠", "digestive", ["intestines"],
                             "Lower palm, framed by the colon. For poor absorption.",
                             "掌下部，结肠环绕之中。用于消化吸收不良。"),
    "palm-uterus": ("Uterus / prostate", "子宫·前列腺", "reproductive", ["uterus"],
                    "Thumb side of the wrist crease. For menstrual cramps or prostate discomfort.",
                    "腕横纹桡侧。用于痛经或前列腺不适。"),
    "palm-gonads": ("Reproductive glands", "生殖腺", "reproductive", ["uterus"],
                    "Middle of the wrist crease. For menstrual discomfort.",
                    "腕横纹中部。用于经期不适。"),
    # ---------------------------------------------------------------- back of hand
    "back-throat": ("Throat & trachea", "喉·气管", "respiratory", ["throat", "larynx"],
                    "Back of the thumb's base section. For sore throat and cough.",
                    "拇指近节背面。用于咽痛、咳嗽。"),
    "back-lymph-head": ("Head & neck lymph", "头颈淋巴结", "lymph", ["throat"],
                        "Webs between the fingers. Traditionally for swollen glands and colds.",
                        "各指间指蹼根部。传统用于淋巴结肿大、感冒。"),
    "back-upper-back": ("Upper back & shoulders", "肩背", "musculoskeletal", ["shoulders", "spine"],
                        "Just behind the knuckles. For tight shoulders and upper back.",
                        "掌指关节后方横带。用于肩背紧张。"),
    "back-chest": ("Chest & breast", "胸·乳房", "respiratory", LUNGS + ["heart"],
                   "Upper back of the hand over metacarpals 2–4. For chest tightness.",
                   "手背第2–4掌骨远段。用于胸闷。"),
    "back-diaphragm": ("Diaphragm", "横膈膜", "respiratory", LUNGS,
                       "Band across the middle of the back of the hand. For hiccups and shallow breathing.",
                       "手背中部横带。用于打嗝、呼吸短浅。"),
    "back-ribs": ("Ribs", "肋骨", "musculoskeletal", LUNGS,
                  "Hollows between metacarpals 2–3 and 4–5. For rib-side ache.",
                  "第2、3及第4、5掌骨间凹陷。用于胁肋酸痛。"),
    "back-cervical": ("Cervical spine", "颈椎", "musculoskeletal", ["spine"],
                      "Outer edge of the thumb. For neck stiffness.",
                      "拇指桡侧缘。用于颈椎僵硬。"),
    "back-thoracic": ("Thoracic spine", "胸椎", "musculoskeletal", ["spine"],
                      "Thumb-side edge, upper metacarpal. For upper-back ache.",
                      "手背桡侧缘，第1掌骨上段。用于胸背酸痛。"),
    "back-lumbar": ("Lumbar spine", "腰椎", "musculoskeletal", ["spine"] + KIDNEYS,
                    "Thumb-side edge, lower metacarpal. For lower-back ache.",
                    "手背桡侧缘，第1掌骨下段。用于腰痛。"),
    "back-sacrum": ("Sacrum & coccyx", "骶尾骨", "musculoskeletal", ["spine"],
                    "Thumb-side edge at the wrist. For tailbone and sciatic pain.",
                    "手背桡侧缘近腕处。用于骶尾痛、坐骨神经痛。"),
    "back-shoulder": ("Shoulder joint", "肩关节", "musculoskeletal", ["shoulders"],
                      "Little-finger edge at the knuckle. For shoulder ache.",
                      "第5掌指关节尺侧。用于肩痛。"),
    "back-elbow": ("Elbow", "肘关节", "musculoskeletal", ["shoulders"],
                   "Little-finger edge, middle of metacarpal 5. For elbow strain.",
                   "第5掌骨尺侧中部。用于肘部劳损。"),
    "back-knee": ("Knee", "膝关节", "musculoskeletal", [],
                  "Little-finger edge, lower metacarpal 5. For knee ache.",
                  "第5掌骨尺侧下段。用于膝痛。"),
    "back-hip": ("Hip", "髋关节", "musculoskeletal", ["spine"],
                 "Little-finger edge at the wrist. For hip ache.",
                 "腕背尺侧缘。用于髋痛。"),
    "back-lymph-upper": ("Upper-body lymph", "上身淋巴结", "lymph", ["spleen"],
                         "Hollow on the little-finger side of the back of the wrist. Traditionally for fever and swelling.",
                         "腕背尺侧凹陷。传统用于发热、肿胀。"),
    "back-lymph-lower": ("Lower-body lymph", "下身淋巴结", "lymph", ["spleen"],
                         "Hollow on the thumb side of the back of the wrist. Traditionally for leg swelling.",
                         "腕背桡侧凹陷。传统用于下肢水肿。"),
    "back-groin": ("Groin & fallopian tubes", "腹股沟·输卵管", "reproductive", ["uterus"],
                   "Across the back of the wrist. Traditionally for groin and pelvic discomfort.",
                   "腕背横带。传统用于腹股沟、盆腔不适。"),
    "back-hegu": ("Hegu (LI4)", "合谷", "head", ["brain", "face"],
                  "Between metacarpals 1 and 2, level with the middle of the 2nd. The classic point for headache, toothache and face pain. Avoid in pregnancy.",
                  "第1、2掌骨间，第2掌骨中点桡侧。头痛、牙痛、面痛常用穴。孕妇忌按。"),
    "back-luozhen": ("Luozhen (EX-UE8)", "落枕", "musculoskeletal", ["spine", "shoulders"],
                     "Between metacarpals 2 and 3, just behind the knuckles. Press while slowly turning the head for a stiff neck.",
                     "第2、3掌骨间，掌指关节后。落枕时边按边缓慢转头。"),
    "back-zhongzhu": ("Zhongzhu (SJ3)", "中渚", "senses", ["ears"],
                      "Between metacarpals 4 and 5, behind the knuckles. For ringing ears and one-sided headache.",
                      "第4、5掌骨间，掌指关节后。用于耳鸣、偏头痛。"),
    "back-yemen": ("Yemen (SJ2)", "液门", "senses", ["throat", "ears"],
                   "Web between ring and little fingers. For sore throat and ear problems.",
                   "无名指与小指指蹼缘。用于咽喉肿痛、耳病。"),
    "back-houxi": ("Houxi (SI3)", "后溪", "musculoskeletal", ["spine"],
                   "Little-finger edge, behind the knuckle. For stiff neck and upper-back pain.",
                   "小指尺侧，第5掌指关节后。用于颈项强痛、上背痛。"),
    "back-yaotong": ("Yaotongdian (EX-UE7)", "腰痛点", "musculoskeletal", ["spine"] + KIDNEYS,
                     "Two points between metacarpals 2–3 and 4–5, halfway to the wrist. For acute low-back strain.",
                     "第2、3及第4、5掌骨间，掌指关节与腕横纹中点。用于急性腰扭伤。"),
    "back-yangxi": ("Yangxi (LI5)", "阳溪", "head", ["brain"],
                    "Thumb end of the wrist crease, in the hollow. For wrist pain, headache and toothache.",
                    "腕背横纹桡侧凹陷中。用于腕痛、头痛、牙痛。"),
    "back-yangchi": ("Yangchi (SJ4)", "阳池", "urinary", KIDNEYS,
                     "Middle of the back wrist crease, little-finger side. For wrist pain and cold hands.",
                     "腕背横纹中，指伸肌腱尺侧凹陷。用于腕痛、手足怕冷。"),
    "back-waiguan": ("Waiguan (SJ5)", "外关", "head", ["brain", "ears"],
                     "Two thumb-widths above the wrist crease, between the forearm bones. For headache, ear and wrist pain.",
                     "腕背横纹上2寸，尺桡骨之间。用于头痛、耳病、腕痛。"),
    # ---------------------------------------------------------------- ear: helix
    "ear-apex": ("Ear apex (HX6,7i)", "耳尖", "head", ["brain", "heart"],
                 "Top of the helix. Traditionally pricked to bring down fever and high blood pressure.",
                 "耳轮顶端。传统点刺用于退热、降压。"),
    "ear-center": ("Ear center (HX1)", "耳中", "digestive", ["stomach"],
                   "The helix root crossing the bowl. Traditionally for hiccups and itchy skin.",
                   "耳轮脚。传统用于呃逆、皮肤瘙痒。"),
    "ear-rectum": ("Rectum (HX2)", "直肠", "digestive", ["intestines"],
                   "Helix just above its root. For constipation and piles.",
                   "耳轮脚上方的耳轮。用于便秘、痔疮。"),
    "ear-urethra": ("Urethra (HX3)", "尿道", "urinary", ["bladder"],
                    "Helix level with the lower bowl. For frequent or urgent urination.",
                    "直肠区上方的耳轮。用于尿频、尿急。"),
    "ear-ext-genitals": ("External genitals (HX4)", "外生殖器", "reproductive", ["uterus"],
                         "Helix level with the inferior crus. Traditionally for genital itching and discomfort.",
                         "与对耳轮下脚相对的耳轮。传统用于外阴瘙痒、不适。"),
    "ear-anus": ("Anus (HX5)", "肛门", "digestive", ["intestines"],
                 "Helix level with the triangular fossa. For piles and anal discomfort.",
                 "与三角窝相对的耳轮。用于痔疮、肛门不适。"),
    "ear-helix": ("Helix 1–4 (HX9–12)", "轮1–轮4", "lymph", ["throat"],
                  "Back rim of the helix down to the lobe. Traditionally pricked for fever and sore throat.",
                  "耳轮后缘至耳垂。传统点刺用于发热、咽痛。"),
    # ---------------------------------------------------------------- ear: scapha
    "ear-finger": ("Finger (SF1)", "指", "musculoskeletal", ["shoulders"],
                   "Top of the scapha. For finger pain and numbness.",
                   "耳舟上部。用于手指疼痛、麻木。"),
    "ear-wind-stream": ("Wind stream (SF1,2i)", "风溪", "lymph", ["sinuses"],
                        "Between the finger and wrist areas. Traditionally for hives, hay fever and itch.",
                        "指区与腕区之间。传统用于荨麻疹、过敏性鼻炎、瘙痒。"),
    "ear-wrist": ("Wrist (SF2)", "腕", "musculoskeletal", ["shoulders"],
                  "Upper scapha, below the finger area. For wrist pain.",
                  "耳舟指区下方。用于腕部疼痛。"),
    "ear-elbow": ("Elbow (SF3)", "肘", "musculoskeletal", ["shoulders"],
                  "Middle of the scapha. For elbow and arm pain.",
                  "耳舟中部。用于肘臂疼痛。"),
    "ear-shoulder": ("Shoulder (SF4,5)", "肩", "musculoskeletal", ["shoulders"],
                     "Lower scapha. For stiff or frozen shoulder.",
                     "耳舟下部。用于肩周炎、肩痛。"),
    "ear-clavicle": ("Clavicle (SF6)", "锁骨", "musculoskeletal", ["shoulders"],
                     "Bottom of the scapha. For collarbone and shoulder ache.",
                     "耳舟最下部。用于锁骨、肩部酸痛。"),
    # ---------------------------------------------------------------- ear: antihelix
    "ear-heel": ("Heel (AH1)", "跟", "musculoskeletal", [],
                 "Front tip of the superior crus. For heel pain.",
                 "对耳轮上脚前上部。用于足跟痛。"),
    "ear-toe": ("Toe (AH2)", "趾", "musculoskeletal", [],
                "Back tip of the superior crus. For toe pain.",
                "对耳轮上脚后上部。用于足趾疼痛。"),
    "ear-ankle": ("Ankle (AH3)", "踝", "musculoskeletal", [],
                  "Superior crus, below heel and toe. For ankle sprain and pain.",
                  "对耳轮上脚，跟、趾区下方。用于踝关节扭伤、疼痛。"),
    "ear-knee": ("Knee (AH4)", "膝", "musculoskeletal", [],
                 "Middle third of the superior crus. For knee pain.",
                 "对耳轮上脚中1/3。用于膝关节疼痛。"),
    "ear-hip": ("Hip (AH5)", "髋", "musculoskeletal", ["spine"],
                "Lower third of the superior crus. For hip pain.",
                "对耳轮上脚下1/3。用于髋关节疼痛。"),
    "ear-sciatic": ("Sciatic nerve (AH6)", "坐骨神经", "musculoskeletal", ["spine"],
                    "Front two-thirds of the inferior crus. For sciatica.",
                    "对耳轮下脚前2/3。用于坐骨神经痛。"),
    "ear-sympathetic": ("Sympathetic (AH6a)", "交感", "head", ["heart", "stomach"],
                        "Front tip of the inferior crus, under the helix. For spasms, palpitations, stomach cramps.",
                        "对耳轮下脚前端与耳轮内缘交界处。用于胃肠痉挛、心悸。"),
    "ear-gluteal": ("Gluteal (AH7)", "臀", "musculoskeletal", ["spine"],
                    "Back third of the inferior crus. For buttock and sciatic pain.",
                    "对耳轮下脚后1/3。用于臀部疼痛、坐骨神经痛。"),
    "ear-abdomen": ("Abdomen (AH8)", "腹", "digestive", ["intestines", "stomach"],
                    "Upper antihelix body, bowl side. For bloating and period pain.",
                    "对耳轮体前部上2/5。用于腹胀、痛经。"),
    "ear-lumbosacral": ("Lumbosacral spine (AH9)", "腰骶椎", "musculoskeletal", ["spine"],
                        "Upper antihelix body, behind the abdomen area. For low-back pain.",
                        "腹区后方。用于腰骶痛。"),
    "ear-chest": ("Chest (AH10)", "胸", "respiratory", LUNGS + ["heart"],
                  "Middle antihelix body, bowl side. For chest tightness and rib-side pain.",
                  "对耳轮体前部中2/5。用于胸闷、胸胁痛。"),
    "ear-thoracic": ("Thoracic spine (AH11)", "胸椎", "musculoskeletal", ["spine"],
                     "Middle antihelix body, behind the chest area. For upper-back pain.",
                     "胸区后方。用于胸背痛。"),
    "ear-neck": ("Neck (AH12)", "颈", "musculoskeletal", ["throat", "spine"],
                 "Lower antihelix body, bowl side. For a stiff neck.",
                 "对耳轮体前部下1/5。用于落枕、颈项强痛。"),
    "ear-cervical": ("Cervical spine (AH13)", "颈椎", "musculoskeletal", ["spine"],
                     "Lower antihelix body, behind the neck area. For neck pain.",
                     "颈区后方。用于颈椎病、落枕。"),
    # ---------------------------------------------------------------- ear: triangular fossa
    "ear-tf-upper": ("Superior triangular fossa (TF1)", "角窝上", "heart", ["heart"],
                     "Front-upper triangular fossa. Traditionally for high blood pressure.",
                     "三角窝前1/3上部。传统用于高血压。"),
    "ear-genitals": ("Internal genitals (TF2)", "内生殖器", "reproductive", ["uterus"],
                     "Front-lower triangular fossa. For menstrual problems.",
                     "三角窝前1/3下部。用于月经不调、痛经。"),
    "ear-tf-middle": ("Middle triangular fossa (TF3)", "角窝中", "respiratory", LUNGS,
                      "Middle third of the triangular fossa. Traditionally for wheezing and cough.",
                      "三角窝中1/3。传统用于哮喘、咳嗽。"),
    "ear-shenmen": ("Shenmen (TF4)", "神门", "head", ["brain"],
                    "Back-upper triangular fossa. The calming point: stress, anxiety, poor sleep, pain.",
                    "三角窝后1/3上部。安神要穴：压力、焦虑、失眠、疼痛。"),
    "ear-pelvis": ("Pelvis (TF5)", "盆腔", "reproductive", ["uterus", "bladder"],
                   "Back-lower triangular fossa. For pelvic and lower-abdominal pain.",
                   "三角窝后1/3下部。用于盆腔炎、下腹痛。"),
    # ---------------------------------------------------------------- ear: tragus
    "ear-upper-tragus": ("Upper tragus (TG1)", "上屏", "senses", ["throat", "sinuses"],
                         "Upper half of the tragus, outer face. Traditionally for sore throat and a blocked nose.",
                         "耳屏外侧面上1/2。传统用于咽炎、鼻塞。"),
    "ear-lower-tragus": ("Lower tragus (TG2)", "下屏", "senses", ["sinuses"],
                         "Lower half of the tragus, outer face. Traditionally for a runny nose.",
                         "耳屏外侧面下1/2。传统用于鼻炎、流涕。"),
    "ear-tragus-apex": ("Tragus apex (TG1p)", "屏尖", "head", ["face", "brain"],
                        "Upper tip of the tragus. Traditionally pricked for fever and toothache.",
                        "耳屏游离缘上部尖端。传统点刺用于发热、牙痛。"),
    "ear-nose": ("External nose (TG1,2i)", "外鼻", "senses", ["sinuses"],
                 "Middle of the tragus, outer face. For a blocked or runny nose.",
                 "耳屏外侧面中部。用于鼻塞、流涕。"),
    "ear-adrenal": ("Adrenal (TG2p)", "肾上腺", "endocrine", ["adrenals"],
                    "Lower tip of the tragus. Traditionally for inflammation, allergy and low blood pressure.",
                    "耳屏游离缘下部尖端。传统用于炎症、过敏、低血压。"),
    "ear-throat": ("Throat (TG3)", "咽喉", "senses", ["throat", "larynx"],
                   "Inner face of the tragus, upper half. For sore throat and hoarseness.",
                   "耳屏内侧面上1/2。用于咽痛、声音嘶哑。"),
    "ear-inner-nose": ("Internal nose (TG4)", "内鼻", "senses", ["sinuses"],
                       "Inner face of the tragus, lower half. For a blocked nose and sinus pressure.",
                       "耳屏内侧面下1/2。用于鼻塞、鼻窦炎。"),
    # ---------------------------------------------------------------- ear: antitragus
    "ear-forehead": ("Forehead (AT1)", "额", "head", ["brain", "sinuses"],
                     "Front of the antitragus. For frontal headache and dizziness.",
                     "对耳屏外侧面前部。用于前额痛、头晕。"),
    "ear-temple": ("Temple (AT2)", "颞", "head", ["brain"],
                   "Middle of the antitragus. For one-sided headache.",
                   "对耳屏外侧面中部。用于偏头痛。"),
    "ear-occiput": ("Occiput (AT3)", "枕", "head", ["brain", "spine"],
                    "Back of the antitragus. For back-of-head pain and dizziness.",
                    "对耳屏外侧面后部。用于后头痛、眩晕。"),
    "ear-subcortex": ("Subcortex (AT4)", "皮质下", "head", ["brain"],
                      "Inner face of the antitragus. For pain, poor sleep and nervous tension.",
                      "对耳屏内侧面。用于疼痛、失眠、神经紧张。"),
    "ear-antitragus-apex": ("Antitragus apex (AT1,2,4i)", "对屏尖", "respiratory", LUNGS,
                            "Tip of the antitragus. Traditionally for wheezing and mumps.",
                            "对耳屏游离缘尖端。传统用于哮喘、腮腺炎。"),
    "ear-brainstem": ("Brainstem (AT3,4i)", "脑干", "head", ["brain"],
                      "Notch between the antitragus and antihelix. Traditionally for dizziness and headache.",
                      "轮屏切迹处。传统用于眩晕、头痛。"),
    # ---------------------------------------------------------------- ear: concha
    "ear-mouth": ("Mouth (CO1)", "口", "digestive", ["face"],
                  "Under the front of the helix root, by the ear canal. For mouth ulcers and facial twitching.",
                  "耳轮脚下方前1/3，近外耳门。用于口腔溃疡、面肌痉挛。"),
    "ear-esophagus": ("Esophagus (CO2)", "食道", "digestive", ["throat", "stomach"],
                      "Under the middle of the helix root. For a lump-in-the-throat feeling and heartburn.",
                      "耳轮脚下方中1/3。用于梅核气、烧心。"),
    "ear-cardia": ("Cardia (CO3)", "贲门", "digestive", ["stomach"],
                   "Under the back of the helix root. For nausea and acid.",
                   "耳轮脚下方后1/3。用于恶心、反酸。"),
    "ear-stomach": ("Stomach (CO4)", "胃", "digestive", ["stomach"],
                    "Where the helix root ends. For stomach ache, nausea, acid.",
                    "耳轮脚消失处。用于胃痛、恶心、反酸。"),
    "ear-duodenum": ("Duodenum (CO5)", "十二指肠", "digestive", ["stomach", "intestines"],
                     "Above the helix root, back third. For duodenal ulcer pain.",
                     "耳轮脚上方后1/3。用于十二指肠溃疡疼痛。"),
    "ear-small-intestine": ("Small intestine (CO6)", "小肠", "digestive", ["intestines"],
                            "Above the helix root, middle third. For poor digestion.",
                            "耳轮脚上方中1/3。用于消化不良。"),
    "ear-large-intestine": ("Large intestine (CO7)", "大肠", "digestive", ["intestines"],
                            "Above the helix root, front third. For constipation.",
                            "耳轮脚上方前1/3。用于便秘、腹泻。"),
    "ear-appendix": ("Appendix (CO6,7i)", "阑尾", "digestive", ["appendix"],
                     "Between the small and large intestine areas. Traditionally for lower-right belly pain.",
                     "小肠区与大肠区之间。传统用于右下腹痛。"),
    "ear-cymba-angle": ("Angle of cymba (CO8)", "艇角", "reproductive", ["uterus"],
                        "Front corner of the upper bowl, under the inferior crus. Traditionally for prostate trouble.",
                        "对耳轮下脚下方前部。传统用于前列腺不适。"),
    "ear-bladder": ("Bladder (CO9)", "膀胱", "urinary", ["bladder"],
                    "Upper bowl under the inferior crus, middle. For frequent urination.",
                    "对耳轮下脚下方中部。用于尿频、尿急。"),
    "ear-ureter": ("Ureter (CO9,10i)", "输尿管", "urinary", KIDNEYS + ["bladder"],
                   "Between the bladder and kidney areas. For urinary discomfort.",
                   "膀胱区与肾区之间。用于排尿不畅。"),
    "ear-kidney": ("Kidney (CO10)", "肾", "urinary", KIDNEYS,
                   "Upper bowl under the inferior crus, back. For fatigue, low back ache, ringing ears.",
                   "对耳轮下脚下方后部。用于疲劳、腰酸、耳鸣。"),
    "ear-pancreas": ("Pancreas & gallbladder (CO11)", "胰胆", "digestive", ["pancreas", "gallbladder"],
                     "Back-upper cymba. For indigestion and a bitter taste.",
                     "耳甲艇后上部。用于消化不良、口苦。"),
    "ear-liver": ("Liver (CO12)", "肝", "digestive", ["liver"],
                  "Back-lower cymba. For irritability, tired or dry eyes.",
                  "耳甲艇后下部。用于烦躁易怒、眼睛干涩疲劳。"),
    "ear-spleen": ("Spleen (CO13)", "脾", "digestive", ["spleen"],
                   "Back-upper cavum. TCM spleen: appetite, digestion, fatigue.",
                   "耳甲腔后上部。中医之脾：食欲、消化、乏力。"),
    "ear-heart": ("Heart (CO15)", "心", "heart", ["heart"],
                  "Center of the cavum. For palpitations and restless sleep.",
                  "耳甲腔正中凹陷处。用于心悸、心烦失眠。"),
    "ear-trachea": ("Trachea (CO16)", "气管", "respiratory", ["throat", "larynx"] + LUNGS,
                    "Between the heart area and the ear canal. For cough.",
                    "心区与外耳门之间。用于咳嗽、气喘。"),
    "ear-lung": ("Lung (CO14)", "肺", "respiratory", LUNGS,
                 "Around the heart and trachea areas. For cough; traditionally also skin and quitting smoking.",
                 "心、气管区周围。用于咳嗽，传统亦用于皮肤病、戒烟。"),
    "ear-sanjiao": ("Sanjiao (CO17)", "三焦", "digestive", ["stomach", "intestines", "bladder"],
                    "Bottom of the cavum, behind the canal. TCM water passages: bloating, swelling.",
                    "外耳门后下方。中医三焦：腹胀、水肿。"),
    "ear-endocrine": ("Endocrine (CO18)", "内分泌", "endocrine", ["pancreas", "thyroid"],
                      "Inside the notch below the tragus. Said to regulate hormones.",
                      "屏间切迹内，耳甲腔底部。传统认为可调节内分泌。"),
    # ---------------------------------------------------------------- ear: lobule
    "ear-teeth": ("Teeth (LO1)", "牙", "senses", ["face"],
                  "Lobe square 1. For toothache.",
                  "耳垂1区。用于牙痛。"),
    "ear-tongue": ("Tongue (LO2)", "舌", "senses", ["face"],
                   "Lobe square 2. Traditionally for tongue and mouth sores.",
                   "耳垂2区。传统用于舌炎、口腔溃疡。"),
    "ear-jaw": ("Jaw (LO3)", "颌", "senses", ["face"],
                "Lobe square 3. For toothache and jaw joint pain.",
                "耳垂3区。用于牙痛、颞颌关节痛。"),
    "ear-lobe-front": ("Anterior ear lobe (LO4)", "垂前", "head", ["brain", "face"],
                       "Lobe square 4. Traditionally for toothache and restless sleep.",
                       "耳垂4区。传统用于牙痛、神经衰弱。"),
    "ear-eye": ("Eye (LO5)", "眼", "senses", ["eyes"],
                "Center square of the lobe. For tired, red or dry eyes.",
                "耳垂5区正中。用于眼疲劳、红肿、干涩。"),
    "ear-inner-ear": ("Inner ear (LO6)", "内耳", "senses", ["ears"],
                      "Lobe square 6. For ringing ears and dizziness.",
                      "耳垂6区。用于耳鸣、眩晕。"),
    "ear-cheek": ("Cheek (LO5,6i)", "面颊", "senses", ["face"],
                  "Between the eye and inner-ear squares. For facial pain and acne.",
                  "耳垂眼区与内耳区之间。用于面痛、痤疮。"),
    "ear-tonsil": ("Tonsil (LO7,8,9)", "扁桃体", "lymph", ["throat"],
                   "Bottom row of the lobe. For swollen tonsils and sore throat.",
                   "耳垂7、8、9区。用于扁桃体肿痛、咽痛。"),
    # ---------------------------------------------------------------- sole
    "sole-brain": ("Brain", "大脑", "head", ["brain"],
                   "Big-toe pad (left foot ↔ right brain). For headache, dizziness, poor sleep.",
                   "拇趾趾腹（左脚对应右脑）。用于头痛、头晕、失眠。"),
    "sole-pituitary": ("Pituitary", "垂体", "endocrine", ["brain"],
                       "Center of the big-toe pad. Said to balance hormones.",
                       "拇趾趾腹正中。传统认为可调节内分泌。"),
    "sole-cerebellum": ("Cerebellum & brainstem", "小脑·脑干", "head", ["brain"],
                        "Lower outer part of the big-toe pad. Traditionally for balance and dizziness.",
                        "拇趾趾腹外侧下部。传统用于平衡失调、眩晕。"),
    "sole-trigeminal": ("Trigeminal nerve", "三叉神经", "head", ["face", "brain"],
                        "Upper outer edge of the big-toe pad. For face and one-sided head pain.",
                        "拇趾趾腹外侧上部。用于面痛、偏头痛。"),
    "sole-nose": ("Nose", "鼻", "senses", ["sinuses"],
                  "Inner edge of the big-toe pad. For a blocked or runny nose.",
                  "拇趾趾腹内侧缘。用于鼻塞、流涕。"),
    "sole-sinuses": ("Frontal sinuses", "额窦", "senses", ["sinuses"],
                     "Pads of toes 2–5. For a blocked nose and frontal headache.",
                     "第2–5趾趾腹。用于鼻塞、前额头痛。"),
    "sole-eyes": ("Eyes", "眼", "senses", ["eyes"],
                  "Base of toes 2 and 3. For tired, strained eyes.",
                  "第2、3趾根部。用于眼疲劳。"),
    "sole-ears": ("Ears", "耳", "senses", ["ears"],
                  "Base of toes 4 and 5. For ringing ears.",
                  "第4、5趾根部。用于耳鸣。"),
    "sole-neck": ("Neck", "颈项", "musculoskeletal", ["throat", "spine"],
                  "Base of the big toe. For a stiff neck.",
                  "拇趾根部。用于颈项僵硬。"),
    "sole-thyroid": ("Thyroid", "甲状腺", "endocrine", ["thyroid"],
                     "Ball of the big toe. Said to regulate metabolism.",
                     "拇趾球部（第1跖骨头）。传统认为可调节代谢。"),
    "sole-parathyroid": ("Parathyroid", "甲状旁腺", "endocrine", ["thyroid"],
                         "Inner edge of the big-toe joint. Traditionally for cramps and calcium balance.",
                         "第1跖趾关节内侧。传统用于抽筋、钙质平衡。"),
    "sole-cervical": ("Cervical spine", "颈椎", "musculoskeletal", ["spine"],
                      "Inner edge of the big toe. The spine runs down the inner arch. For neck pain.",
                      "拇趾内侧缘，脊柱沿足弓内侧分布。用于颈痛。"),
    "sole-thoracic": ("Thoracic spine", "胸椎", "musculoskeletal", ["spine"],
                      "Inner edge along the first metatarsal. For upper-back ache.",
                      "足内侧缘，沿第1跖骨。用于胸背酸痛。"),
    "sole-lumbar": ("Lumbar spine", "腰椎", "musculoskeletal", ["spine"] + KIDNEYS,
                    "Inner edge of the arch. For lower-back pain.",
                    "足弓内侧缘。用于腰痛。"),
    "sole-sacrum": ("Sacrum & coccyx", "骶尾骨", "musculoskeletal", ["spine"],
                    "Inner edge of the heel. For tailbone and sciatic pain.",
                    "足跟内侧缘。用于骶尾痛、坐骨神经痛。"),
    "sole-trapezius": ("Trapezius", "斜方肌", "musculoskeletal", ["shoulders"],
                       "Band just below toes 2–5. For tight shoulders.",
                       "第2–5趾根下方横带。用于肩颈紧张。"),
    "sole-lungs": ("Lungs & bronchi", "肺·支气管", "respiratory", LUNGS,
                   "Ball of the foot under toes 2–5. For cough and chest tightness.",
                   "第2–5趾下方的前脚掌。用于咳嗽、胸闷。"),
    "sole-shoulder": ("Shoulder", "肩", "musculoskeletal", ["shoulders"],
                      "Outer edge at the little-toe joint. For stiff shoulders.",
                      "第5跖趾关节外侧。用于肩部僵硬。"),
    "sole-elbow": ("Elbow", "肘", "musculoskeletal", ["shoulders"],
                   "Outer edge at the bump of metatarsal 5. For elbow strain.",
                   "足外侧缘第5跖骨粗隆处。用于肘部劳损。"),
    "sole-knee": ("Knee", "膝", "musculoskeletal", [],
                  "Outer edge in front of the heel. For knee ache.",
                  "足外侧缘足跟前方。用于膝痛。"),
    "sole-solar-plexus": ("Solar plexus", "腹腔神经丛", "head", ["stomach", "brain"],
                          "Just below the ball, in the middle. Pressed to calm nerves and a knotted stomach.",
                          "前脚掌下方正中。按压用于缓解紧张、胃部痉挛。"),
    "sole-heart": ("Heart", "心", "heart", ["heart"],
                   "Left foot only, under the ball below toes 4–5. For palpitations.",
                   "仅左脚，第4、5趾下方前脚掌之后。用于心悸。"),
    "sole-spleen": ("Spleen", "脾", "digestive", ["spleen"],
                    "Left foot only, below the heart zone. TCM spleen: appetite, digestion.",
                    "仅左脚，心反射区下方。中医之脾：食欲、消化。"),
    "sole-liver": ("Liver", "肝", "digestive", ["liver"],
                   "Right foot only, under the ball below toes 4–5. Said to support detox.",
                   "仅右脚，第4、5趾下方前脚掌之后。传统认为可助肝排毒。"),
    "sole-gallbladder": ("Gallbladder", "胆囊", "digestive", ["gallbladder"],
                         "Right foot only, inside the lower liver zone. For a bitter taste and fatty-food discomfort.",
                         "仅右脚，肝反射区下部之中。用于口苦、油腻后不适。"),
    "sole-stomach": ("Stomach", "胃", "digestive", ["stomach"],
                     "Below the ball of the big toe. For indigestion and bloating.",
                     "拇趾球下方。用于消化不良、胃胀。"),
    "sole-pancreas": ("Pancreas", "胰", "digestive", ["pancreas"],
                      "Below the stomach zone. Traditionally linked to blood sugar.",
                      "胃反射区下方。传统上与血糖调节相关。"),
    "sole-duodenum": ("Duodenum", "十二指肠", "digestive", ["stomach", "intestines"],
                      "Below the pancreas zone. For stomach ache after meals.",
                      "胰反射区下方。用于餐后胃痛。"),
    "sole-adrenal": ("Adrenals", "肾上腺", "endocrine", ["adrenals"],
                     "Just above the kidney zone. For inflammation and allergy.",
                     "肾反射区上方。用于炎症、过敏。"),
    "sole-yongquan": ("Yongquan (KI1)", "涌泉", "urinary", KIDNEYS + ["brain"],
                      "Hollow at the front third of the sole when the toes curl. Grounding point: insomnia, dizziness, hot feet.",
                      "足底前1/3凹陷处（卷足时）。用于失眠、头晕、足心发热。"),
    "sole-kidneys": ("Kidneys", "肾", "urinary", KIDNEYS,
                     "Middle of the sole. For fatigue and lower-back ache.",
                     "足底中部。用于疲劳、腰酸。"),
    "sole-ureter": ("Ureter", "输尿管", "urinary", KIDNEYS + ["bladder"],
                    "Line from the kidney zone down to the bladder. For urinary discomfort.",
                    "肾至膀胱的斜线带。用于排尿不畅。"),
    "sole-bladder": ("Bladder", "膀胱", "urinary", ["bladder"],
                     "Inner edge where the arch meets the heel. For frequent urination.",
                     "足底内侧，足弓与足跟交界处。用于尿频。"),
    "sole-colon": ("Transverse colon", "横结肠", "digestive", ["intestines"],
                   "Band across the middle of the sole. For constipation and wind.",
                   "足底中部横带。用于便秘、腹胀。"),
    "sole-colon-asc": ("Ascending colon", "升结肠", "digestive", ["intestines"],
                       "Right foot only, outer edge of the arch. For constipation.",
                       "仅右脚，足弓外侧纵带。用于便秘。"),
    "sole-appendix": ("Appendix & ileocecal valve", "阑尾·回盲瓣", "digestive", ["appendix", "intestines"],
                      "Right foot only, bottom of the ascending colon, in front of the heel. Traditionally for lower-right bloating.",
                      "仅右脚，升结肠下端，足跟前方。传统用于右下腹胀。"),
    "sole-colon-desc": ("Descending & sigmoid colon", "降结肠·乙状结肠", "digestive", ["intestines"],
                        "Left foot only, down the outer arch then across in front of the heel. For constipation.",
                        "仅左脚，足弓外侧下行再横过足跟前方。用于便秘。"),
    "sole-rectum": ("Rectum", "直肠·肛门", "digestive", ["intestines"],
                    "Left foot only, inner end of the sigmoid band. For constipation and piles.",
                    "仅左脚，乙状结肠带内侧端。用于便秘、痔疮。"),
    "sole-small-intestine": ("Small intestine", "小肠", "digestive", ["intestines"],
                             "Lower arch, framed by the colon. For poor absorption.",
                             "足弓下部，结肠环绕之中。用于消化吸收不良。"),
    "sole-sciatic": ("Sciatic nerve", "坐骨神经", "musculoskeletal", ["spine"],
                     "Band across the front of the heel. For sciatic and leg pain.",
                     "足跟前缘横带。用于坐骨神经痛、腿痛。"),
    "sole-insomnia": ("Insomnia point", "失眠点", "head", ["brain"],
                      "Front of the heel pad, center. For poor sleep.",
                      "足跟前部正中。用于失眠。"),
    "sole-gonads": ("Reproductive glands", "生殖腺", "reproductive", ["uterus"],
                    "Center of the heel. For menstrual discomfort.",
                    "足跟正中。用于经期不适。"),
    # ---------------------------------------------------------------- top of foot
    "top-jaw-upper": ("Upper jaw", "上颌", "senses", ["face"],
                      "Top of the big toe, just past the joint crease. For toothache and gum ache.",
                      "拇趾背面，趾间关节横纹前方。用于牙痛、牙龈痛。"),
    "top-jaw-lower": ("Lower jaw", "下颌", "senses", ["face"],
                      "Top of the big toe, just behind the joint crease. For jaw tension and toothache.",
                      "拇趾背面，趾间关节横纹后方。用于下颌紧张、牙痛。"),
    "top-tonsils": ("Tonsils", "扁桃体", "lymph", ["throat"],
                    "Top of the big toe's base, either side of the tendon. For sore throat.",
                    "拇趾近节背面，肌腱两侧。用于咽喉肿痛。"),
    "top-throat": ("Throat & trachea", "喉·气管", "respiratory", ["throat", "larynx"],
                   "Top of the big-toe joint. For sore throat, hoarseness and cough.",
                   "第1跖趾关节背面。用于咽痛、声音嘶哑、咳嗽。"),
    "top-chest-lymph": ("Chest lymph", "胸部淋巴结", "lymph", ["heart"] + LUNGS,
                        "Groove between metatarsals 1 and 2. Traditionally for chest and breast swelling.",
                        "第1、2跖骨间缝。传统用于胸部、乳房胀痛。"),
    "top-chest": ("Chest & breast", "胸·乳房", "respiratory", LUNGS + ["heart"],
                  "Middle of the foot top, over metatarsals 2–4. For chest tightness.",
                  "足背第2–4跖骨中段。用于胸闷。"),
    "top-balance": ("Inner ear & balance", "内耳迷路", "senses", ["ears"],
                    "Groove between metatarsals 4 and 5, near the toes. For dizziness and motion sickness.",
                    "第4、5跖骨间缝远端。用于头晕、晕车。"),
    "top-shoulder-blade": ("Shoulder blade", "肩胛骨", "musculoskeletal", ["shoulders"],
                           "Over the back half of metatarsals 4 and 5. For shoulder-blade ache.",
                           "第4、5跖骨近端1/2。用于肩胛酸痛。"),
    "top-diaphragm": ("Diaphragm", "横膈膜", "respiratory", LUNGS,
                      "Band across the foot top where the metatarsals meet the midfoot. For hiccups and bloating.",
                      "足背跖骨与跗骨交界横带。用于打嗝、腹胀。"),
    "top-ribs": ("Ribs", "肋骨", "musculoskeletal", LUNGS,
                 "Hollows either side of the midfoot, below the diaphragm band. For rib-side ache.",
                 "足背中部两侧，横膈膜下方。用于胁肋酸痛。"),
    "top-lymph-upper": ("Upper-body lymph", "上身淋巴结", "lymph", ["spleen"],
                        "Hollow in front of the outer ankle bone. Traditionally for fever and swelling.",
                        "外踝前凹陷。传统用于发热、肿胀。"),
    "top-lymph-lower": ("Lower-body lymph", "下身淋巴结", "lymph", ["spleen"],
                        "Hollow in front of the inner ankle bone. Traditionally for leg swelling.",
                        "内踝前凹陷。传统用于下肢水肿。"),
    "top-fallopian": ("Fallopian tubes / vas deferens", "输卵管·输精管", "reproductive", ["uterus"],
                      "Band across the front of the ankle, bone to bone. Traditionally for pelvic discomfort.",
                      "踝前横带，内外踝之间。传统用于盆腔不适。"),
    "top-xingjian": ("Xingjian (LV2)", "行间", "digestive", ["liver", "eyes"],
                     "Web between the big and second toes. For red eyes, headache, irritability.",
                     "第1、2趾间趾蹼缘。用于目赤、头痛、烦躁。"),
    "top-taichong": ("Taichong (LV3)", "太冲", "digestive", ["liver", "brain"],
                     "Between metatarsals 1 and 2, in the hollow before they meet. For stress, headache, high blood pressure.",
                     "第1、2跖骨间，跖骨结合部前凹陷中。用于情志不畅、头痛、高血压。"),
    "top-neiting": ("Neiting (ST44)", "内庭", "digestive", ["stomach", "face"],
                    "Web between the second and third toes. For toothache and stomach heat.",
                    "第2、3趾间趾蹼缘。用于牙痛、胃热。"),
    "top-zulinqi": ("Zulinqi (GB41)", "足临泣", "head", ["brain", "eyes"],
                    "Between metatarsals 4 and 5, near their base. For one-sided headache and eye pain.",
                    "第4、5跖骨底结合部前方。用于偏头痛、目痛。"),
    "top-jiexi": ("Jiexi (ST41)", "解溪", "digestive", ["stomach", "brain"],
                  "Front of the ankle crease, between the two tendons. For ankle pain, headache, bloating.",
                  "踝关节前横纹中点，两筋之间。用于踝痛、头痛、腹胀。"),
}
