"""build/art3d/<scene>/<style>/*.png → Resources/Illustrations/<scene>/<scene>-*.webp, plus the overlay anchor points
measured in the renders (Sources/Illustrations/Art/SceneMarks.swift). Incremental: pictures not rendered this time stay.

  venv/bin/python scripts/art3d/pack.py [style] [quality]
"""

import json
import re
import sys
from pathlib import Path

from PIL import Image, ImageChops, ImageFilter

ROOT = Path(__file__).resolve().parents[2]
STYLE = sys.argv[1] if len(sys.argv) > 1 else "ink"
QUALITY = int(sys.argv[2]) if len(sys.argv) > 2 else 74
SRC = ROOT / "build" / "art3d"
OUT = ROOT / "Resources" / "Illustrations"
SWIFT = ROOT / "Sources" / "Illustrations" / "Art" / "SceneMarks.swift"


def quiet(im):
    """smooth the grain in the fading floor's alpha (it compresses badly); figure edges stay crisp"""
    a = im.getchannel("A")
    soft = a.filter(ImageFilter.GaussianBlur(5))
    # only where the neighbourhood is floor (no solid figure near): blurred alpha well below opaque
    mask = soft.point(lambda v: 255 if v < 225 else 0).filter(ImageFilter.MinFilter(9))
    im.putalpha(ImageChops.composite(soft, a, mask))
    return im


def packed_marks():
    marks = {}
    if SWIFT.exists():
        for key, body in re.findall(r'^\s*"([^"]+)": \[(.*)\],$', SWIFT.read_text(), re.M):
            marks[key] = {k: [float(x), float(y)] for k, x, y in re.findall(r'"(\w+)": CGPoint\(x: ([-\d.]+), y: ([-\d.]+)\)', body)}
    return marks


def main():
    marks, total = packed_marks(), 0
    for scene in sorted(p.parent.name for p in SRC.glob(f"*/{STYLE}")):
        dst_dir = OUT / scene
        dst_dir.mkdir(parents=True, exist_ok=True)
        size = 0
        for png in sorted((SRC / scene / STYLE).glob("*.png")):
            if png.stem.endswith("-close"):
                continue
            key = f"{scene}-{png.stem}"
            dst = dst_dir / f"{key}.webp"
            quiet(Image.open(png).convert("RGBA")).save(dst, "WEBP", quality=QUALITY, method=6, alpha_quality=70)
            size += dst.stat().st_size
            js = png.with_suffix(".json")
            if js.exists():
                marks[key] = json.loads(js.read_text())
        total += size
        print(f"{scene}: {size // 1024} KB")
    print(f"total {total / 1024:.0f} KB")
    lines = ["import CoreGraphics", "",
             "// Generated by scripts/art3d/pack.py — overlay anchor points (viewBox 360 × 300) measured in the scene renders.",
             "enum SceneMarks {", "    static let marks: [String: [String: CGPoint]] = ["]
    for shot, pts in sorted(marks.items()):
        body = ", ".join(f'"{k}": CGPoint(x: {x}, y: {y})' for k, (x, y) in sorted(pts.items()))
        lines.append(f'        "{shot}": [{body}],')
    lines += ["    ]", "", "    /// anchor points of one picture, e.g. at(\"cpr-adult-2\")", "    static func at(_ key: String) -> [String: CGPoint] { marks[key] ?? [:] }", "}", ""]
    SWIFT.write_text("\n".join(lines))


if __name__ == "__main__":
    main()
